server:
  port: 8081
spring:
  application:
    name: dubbo-coupon-provider
  datasource:
    name: shop
    url: jdbc:mysql://localhost:3306/mq_shop?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      id: dubbo-coupon-provider
      name: dubbo-coupon-provider
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://192.168.139.10:2181;zookeeper://192.168.139.10:2182;zookeeper://192.168.139.10:2183
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20880
#    scan: com.dubboProvide.dubboProvide.service  #服务暴露与发现消费所在的package
# mybatis配置
mybatis:
  mapper-locations: classpath:/org.zhouzhou.mq.mapper/*.xml
  type-aliases-package: org.zhouzhou.mq.pojo

rocketmq:
  name-server: 192.168.139.10:9876 # RocketMQ Namesrv
  # Producer 配置项
  producer:
    group: orderProducerGroup
mq:
  order:
    topic: orderTopic
    consumer:
      group:
        name: order_orderTopic_cancel_group
    tag:
      confirm: order_confirm
      cancel: order_cancel